stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
    outs:
      - data/prepared
  train:
    cmd: python src/train.py
    deps:
      - data/prepared
      - src/train.py
      - data/prepared/obj.data
      - cfg/obj.names
      - cfg/yolo.cfg
    outs:
      - runs/train/backup/yolo_best.weights
  make_json:
    cmd: python src/make_json.py
    deps:
      - src/make_json.py
      - data/prepared/obj.data
      - cfg/obj.names
      - cfg/yolo.cfg
      - runs/train/backup/yolo_best.weights
    outs:
      - runs/eval/result.json
  prepare_gt:
    cmd: python src/make_gt_det.py
    deps:
      - src/make_gt_det.py
      - runs/eval/result.json
      - data/prepared/valid.txt
      - cfg/obj.names
    outs:
      - runs/eval/pascalvoc_gt
      - runs/eval/pascalvoc_det
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - runs/eval/pascalvoc_gt
      - runs/eval/pascalvoc_det
    metrics:
    - runs/eval/results/results.csv:
        cache: false
