stages:
  prepare:
    cmd: python src/darknet_train_helper/remove_all_small_boxes.py && python src/prepare.py && python src/check_datasets.py && python src/featurizer.py
    deps:
      - src/prepare.py
      - cfg/yolo.cfg
    params:
      - prepare.datasets
      - prepare.train_size
      - prepare.seed
      - prepare.classes
      - prepare.thresh
      - prepare.use_default_train_valid
      - prepare.remove_small_boxes
      - prepare.batch
      - prepare.subdivisions
      - prepare.width
      - prepare.height
      - prepare.channels
      - prepare.momentum
      - prepare.decay
      - prepare.learning_rate
      - prepare.max_batches
      - prepare.burn_in
      - prepare.policy
      - prepare.scales
      - prepare.steps
    outs:
      - data/prepared

  train:
    cmd: python src/train.py
    deps:
      - data/prepared
      - src/train.py
      - data/prepared/obj.data
      - cfg/obj.names
      - cfg/yolo.cfg
    outs:
      - runs/train/backup

  make_json:
    cmd: python src/make_json.py
    deps:
      - src/make_json.py
      - data/prepared/obj.data
      - cfg/obj.names
      - cfg/yolo.cfg
      - runs/train/backup
    outs:
      - runs/eval/result.json

  prepare_gt:
    cmd: python src/make_gt_det.py
    deps:
      - src/make_gt_det.py
      - runs/eval/result.json
      - data/prepared/valid.txt
      - cfg/obj.names
    outs:
      - runs/eval/pascalvoc_gt
      - runs/eval/pascalvoc_det

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - runs/eval/pascalvoc_gt
      - runs/eval/pascalvoc_det

    metrics:
      - runs/eval/results/evaluate.json:
          cache: false

    plots:
      - runs/eval/results/axle.json:
          title: axle
          x: recall
          y: precision

      - runs/eval/results/bus.json:
          title: bus
          x: recall
          y: precision
      
      - runs/eval/results/trailer.json:
          title: trailer
          x: recall
          y: precision

      - runs/eval/results/car_carrier_trailer.json:
          title: car_carrier_trailer
          x: recall
          y: precision

      - runs/eval/results/car_carrier.json:
          title: car_carrier
          x: recall
          y: precision

      - runs/eval/results/car_trailer.json:
          title: car_trailer
          x: recall
          y: precision

      - runs/eval/results/car.json:
          title: car
          x: recall
          y: precision

      - runs/eval/results/drawbar.json:
          title: drawbar
          x: recall
          y: precision

      - runs/eval/results/dump_truck_body.json:
          title: dump_truck_body
          x: recall
          y: precision

      - runs/eval/results/motorcycle.json:
          title: motorcycle
          x: recall
          y: precision

      - runs/eval/results/pickup.json:
          title: pickup
          x: recall
          y: precision

      - runs/eval/results/platform_trailer.json:
          title: platform_trailer
          x: recall
          y: precision

      - runs/eval/results/service_vehicle.json:
          title: service_vehicle
          x: recall
          y: precision

      - runs/eval/results/tank_trailer.json:
          title: tank_trailer
          x: recall
          y: precision
      
      - runs/eval/results/truck_cabin.json:
          title: truck_cabin
          x: recall
          y: precision

      - runs/eval/results/truck.json:
          title: truck
          x: recall
          y: precision

      - runs/eval/results/unknown.json:
          title: unknown
          x: recall
          y: precision

      - runs/eval/results/van.json:
          title: van
          x: recall
          y: precision

      - runs/eval/results/results_rpa.png
      - runs/eval/results/results_tfpn.png
