prepare:
  datasets: ["80_test"]
  train_size: 0.80
  seed: 0
  classes: [truck_cabin, tank_trailer, car_carrier, car_trailer, car_carrier_trailer, trailer, platform_trailer, car, motorcycle, bus, truck, pickup, axle, unknown, van, dump_truck_body, service_vehicle, drawbar]
  thresh: 0.5
  remove_small_boxes: True