prepare:
  datasets: [80, 123]
  train_size: 0.75
  seed: 666
  classes: [truck_cabin, tank_trailer, car_carrier, car_trailer, car_carrier_trailer, trailer, platform_trailer, car, motorcycle, bus, truck, pickup, axle, unknown, van, dump_truck_body, service_vehicle, drawbar]
  thresh: 0.5